---
title: Полезные инструменты в Windows
author: ''
date: '2020-03-26'
slug: windows
categories: []
tags:
  - tools
  - Windows
---

# ОС, железо и безопасность
- [1Password]()
- [Advanced PDF Password Recovery]()
- [AOMEI Backupper Professional]()
- [AOMEI Partition Assistant Pro Edition 6.0]()
- [Bitwarden]()
- [CPUID CPU-Z]()
- [Hard Disk Sentinel]()
- [HDD Regenerator]()
- [Melloware PlacesBar Editor]()
- [Paragon HFS+ for Windows]()
- [Passware Kit Forensic 2017]()
- [Password Agent]()
- [Process Hacker 2]()
- [RAMDisk Configuration Utility]()
- [Samsung Magician]()
- [Sysinternals Process Explorer]()
- [UltraISO]()
- [Windows Hotkey Explorer]()

# Работа с файлами
- [Archivarius 3000]()
- [AstroGrep]()
- [Atom]()
- [Bash на Ubuntu]()
- [Brackets]()
- [Bulk Rename Utility]()
- [ConEmu (x64)]()
- [dnGREP]()
- [Duplicate Cleaner Pro]()
- [EmEditor]()
- [Evernote]()
- [Everything]()
- [EXIF ReName]()
- [Far]()
- [Foxit PDF Editor]()
- [IZArc]()
- [Listary]()
- [LogExpert]()
- [mTail]()
- [mTorrent]()
- [ORPALIS PDF Reducer Pro 3]()
- [PowerShell]()
- [Recuva]()
- [Rename-It!]()
- [Resilio Sync]()
- [Search Everything]()
- [SyncToy]()
- [TreeSize]()
- [Typora](https://typora.io/). Минимальный markdown редактор. Win/Mac


# Резервное копирование
- [Arq]()
- [Dropbox]()
- [MEGAsync]()
- [ViceVersa PRO]()

# Разработка
- [DBeaver]()
- [DeepGit]()
- [Falcon SQL Client]()
- [Git Shell]()
- [JetBrains DataGrip]()
- [JetBrains PyCharm]()
- [Postman]()
- [PowerGREP]()
- [SmartGit]()
- [SourceTree]()
- [Tower]()
- [Wing IDE]()


# Сетевые подключения и удаленный доступ
- [Cisco AnyConnect Secure Mobility Client]()
- [Bitvise SSH Client]()
- [OpenConnect-GUI VPN client]()
- [OpenVPN GUI]()
- [PuTTY]()
- [TeamViewer 14]()
- [TripMode]()
- [Windscribe]()
- [WinSCP]()
- [Wireshark]()
- [Xshell 5]()
- [Xshell 6]()


# Мультимедиа
- [AIMP]()
- [Camtasia 9]()
- [Codec Tweak Tool]()
- [KeepVid Pro]()
- [Kid3]()
- [LameXP]()
- [MediaInfo]()
- [Plex Media Server]()
- [Similarity]()
- [SoftorinoYoutubeConverter2]()
- [Tag&Rename]()
- [TigoTago](http://tigotago.com/)
- [VidCoder Beta]()
- [VideoPad Video Editor]()
- [VideoProc]()
- [WALTR2]()
- [XnView]()

# ПО общего назначения

- [ABBYY FineReader 11]()
- [Acrobat Reader DC]()
- [Aurora HDR 2018]()
- [Balsamiq Mockups 3]()
- [CorelDRAW]()
- [Google Chrome NO SANDBOX]()
- [Grammarly]()
- [Inkscape 0.91]()
- [Instant Eyedropper]()
- [iTunes]()
- [Kiwi for Gmail]()
- [LSEConfig]()
- [Luminar 2018]()
- [MarkdownPad 2]()
- [MobileBalance]()
- [NCH Suite]()
- [Nokia PC Suite]()
- [Outlook 2016]()
- [Photoshop 2015]()
- [PowerPoint 2016]()
- [Project 2016]()
- [R]()
- [RStudio]()
- [Skype]()
- [Slack]()
- [Smart Switch]()
- [SmartDown]()
- [Snagit 13]()
- [Steam]()
- [Telegram]()
- [TextPipe Pro Evaluation]()
- [Visio 2016]()
- [WebSite-Watcher]()
- [WhatsApp]()
- [WhereIsIt]()
- [WinDjView]()
- [WinEdt 10]()
- [Wolfram Mathematica 11.3]()
- [Word 2016]()
- [XmlPad]()

